- name: Install required modules for php
  apt:
    name:
      - php
      - libapache2-mod-php
      - php-mysql
    state: present

- name: After installing php ensure apache is restarted
  service:
    name: apache2
    state: restarted

